name = "subscription-master"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "subscription-manager"
database_id = "3e52c5ad-772c-4d5e-a93d-3be58c535463" # We will use local development
migrations_dir = "migrations"
